# Generated by Django 5.0.3 on 2024-04-08 10:27

import django.db.models.deletion
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtor', models.CharField(max_length=50, verbose_name='Автор')),
                ('img', models.ImageField(blank=True, null=True, upload_to=polls.models.img_avtor, verbose_name='Картинка')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=120, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_category', models.CharField(max_length=50, null=True, verbose_name='Категория xарактеристики')),
                ('category', models.CharField(max_length=50, verbose_name='Характеристика')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Описание характерискики')),
            ],
            options={
                'verbose_name': 'Описание характеритики',
                'verbose_name_plural': 'Описание характеритики',
            },
        ),
        migrations.CreateModel(
            name='Tovars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('skidka', models.IntegerField(default=0, verbose_name='Скидка')),
                ('avtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.avtor', verbose_name='Производитель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='specs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Значение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.detail', verbose_name='Характеристика')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tovars')),
            ],
            options={
                'verbose_name': 'Характеристика к товару',
                'verbose_name_plural': 'Характеристики к товару',
            },
        ),
        migrations.CreateModel(
            name='img_tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=polls.models.img_tovar, verbose_name='Картинка')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tovars')),
            ],
            options={
                'verbose_name': 'Картинка к товару',
                'verbose_name_plural': 'Картинки к товарами',
            },
        ),
    ]
