# Generated by Django 5.0.3 on 2024-04-08 11:15

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='category',
            field=models.CharField(max_length=50, unique=True, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.ImageField(upload_to=polls.models.img_tovar, verbose_name='Картинка'),
        ),
    ]
