# Generated by Django 5.0.3 on 2024-04-14 18:52

import django.db.models.deletion
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_detail_category_alter_img_tovar_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avtor',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='avtor',
            name='avtor',
            field=models.CharField(help_text='Введите производителя товара', max_length=50, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(db_index=True, help_text='Введите название категории', max_length=120, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='category',
            field=models.CharField(help_text='Введите характеристику', max_length=50, unique=True, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='details',
            field=models.TextField(blank=True, help_text='Описание характеристики (не обязательно)', null=True, verbose_name='Описание характерискики'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='gl_category',
            field=models.CharField(help_text='Введите категорию характеристики', max_length=50, null=True, verbose_name='Категория xарактеристики'),
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.ImageField(upload_to=polls.models.img_tovar, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='tovar',
            field=models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, to='polls.tovars'),
        ),
        migrations.AlterField(
            model_name='specs',
            name='category',
            field=models.ForeignKey(help_text='Выберите характеристику к товару', on_delete=django.db.models.deletion.CASCADE, to='polls.detail', verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='specs',
            name='description',
            field=models.TextField(help_text='Введите значение характеристики к товару', verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='specs',
            name='tovar',
            field=models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, to='polls.tovars'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='avtor',
            field=models.ForeignKey(help_text='Выберите Производителя товара', on_delete=django.db.models.deletion.PROTECT, to='polls.avtor', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.PROTECT, to='polls.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='cost',
            field=models.IntegerField(help_text='Введите ценну товара', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='name',
            field=models.CharField(help_text='Введите название товара', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='skidka',
            field=models.IntegerField(default=0, help_text='Введите скидку (по умолчанию - 0)', verbose_name='Скидка'),
        ),
    ]
