# Generated by Django 5.0.3 on 2024-04-16 13:18

import django.db.models.deletion
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_avtor_options_alter_avtor_avtor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gl_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gl_category', models.CharField(db_index=True, help_text='Введите название главной категории', max_length=120, verbose_name='Главная категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Главная категория',
                'verbose_name_plural': 'Главные категории',
            },
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.ImageField(null=True, upload_to=polls.models.img_tovar, verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='category',
            name='Gl_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.gl_category', verbose_name='Главная категория'),
        ),
    ]
