# Generated by Django 5.0.3 on 2024-04-25 13:17

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_img_tovar_img_alter_tovars_category_favoritess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.ImageField(null=True, upload_to=polls.models.img_tovar, verbose_name='Картинка'),
        ),
    ]
