# Generated by Django 5.0.3 on 2024-05-01 15:41

import django.db.models.deletion
import polls.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_favoritess_created_at_alter_img_tovar_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.ImageField(null=True, upload_to=polls.models.img_tovar, verbose_name='Картинка'),
        ),
        migrations.CreateModel(
            name='history_tovars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата просмотра товара')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tovars', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История просмотра товаров',
                'verbose_name_plural': 'Истории просмотров товаров',
            },
        ),
    ]
