# Generated by Django 5.0.3 on 2024-05-01 17:01

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_img_tovar_img_history_tovars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovars',
            name='skidka',
        ),
        migrations.AddField(
            model_name='tovars',
            name='skidka_cost',
            field=models.IntegerField(help_text='Введите ценну со скидкой', null=True, verbose_name='Ценна со скидкой'),
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.ImageField(null=True, upload_to=polls.models.img_tovar, verbose_name='Картинка'),
        ),
    ]
