# Generated by Django 5.0.3 on 2024-05-06 15:44

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_tovars_skidka_tovars_skidka_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtor',
            name='slug',
            field=models.SlugField(help_text='если ошибка: поля повторяются. то измениете поле', max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='если ошибка: поля повторяются. то измениете поле', max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='gl_category',
            name='slug',
            field=models.SlugField(help_text='если ошибка: поля повторяются. то измениете поле', max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='cost',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='skidka_cost',
            field=models.IntegerField(help_text='можно оставить пустым', null=True, verbose_name='Ценна со скидкой'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='slug',
            field=models.SlugField(help_text='если ошибка: поля повторяются. то измениете поле', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
