# Generated by Django 5.0.3 on 2024-05-06 16:44

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_detail_cotegory_tovar_alter_img_tovar_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='cotegory_tovar',
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, verbose_name='Картинка или видео'),
        ),
        migrations.AddField(
            model_name='detail',
            name='cotegory_tovar',
            field=models.ManyToManyField(to='polls.category', verbose_name='Категория товара'),
        ),
    ]
