# Generated by Django 5.0.3 on 2024-05-06 17:15

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_img_tovar_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='category',
            field=models.CharField(help_text='Введите характеристику', max_length=50, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, verbose_name='Картинка или видео'),
        ),
    ]
