# Generated by Django 5.0.3 on 2024-05-07 18:52

import django.core.validators
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_detail_cotegory_tovar_alter_img_tovar_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='img_tovar',
            name='is_video',
            field=models.BooleanField(default=False, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
    ]
