# Generated by Django 5.0.3 on 2024-05-29 18:44

import django.core.validators
import django.db.models.deletion
import polls.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_img_tovar_is_video_alter_img_tovar_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specs',
            options={'verbose_name': 'Характеристику к товару', 'verbose_name_plural': 'Характеристики к товару'},
        ),
        migrations.AlterField(
            model_name='detail',
            name='cotegory_tovar',
            field=models.ManyToManyField(blank=True, to='polls.category', verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='is_video',
            field=models.BooleanField(default=False, help_text='ставиться автомитически. если нет, то поставте', verbose_name='Видео'),
        ),
        migrations.CreateModel(
            name='basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('tovar', models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, to='polls.tovars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
