# Generated by Django 5.0.3 on 2024-06-09 17:47

import django.core.validators
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_alter_img_tovar_img_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='img_tovar',
            options={'verbose_name': 'Картинка к товару', 'verbose_name_plural': 'Картинки к товарам'},
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dostavka',
            field=models.CharField(choices=[('collect', 'Собирается'), ('goes', 'Достовляется'), ('delivered', 'Доставлен'), ('received', 'Получен')], max_length=9, verbose_name='Доставка'),
        ),
    ]
