# Generated by Django 5.0.3 on 2024-06-09 17:54

import django.core.validators
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_alter_img_tovar_options_alter_img_tovar_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sposob_dostavka',
            field=models.CharField(choices=[('Pickup', 'Самовывоз'), ('Mail', 'Почта Росси')], default=1, max_length=9, verbose_name='Доставка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
    ]
