# Generated by Django 5.0.3 on 2024-06-10 13:38

import django.core.validators
import django.db.models.deletion
import polls.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_alter_img_tovar_img_alter_tovars_t_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dostavka', models.CharField(choices=[('collect', 'Собирается'), ('goes', 'Достовляется'), ('delivered', 'Доставлен'), ('received', 'Получен')], max_length=9, verbose_name='Доставка')),
                ('sposob_dostavka', models.CharField(choices=[('Pickup', 'Самовывоз'), ('Mail', 'Почта Росси')], max_length=9, verbose_name='Способ доставки')),
                ('tovar_order', models.ManyToManyField(blank=True, to='polls.order_tovars', verbose_name='Товары заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
