# Generated by Django 5.0.3 on 2024-11-18 15:49

import django.core.validators
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_alter_img_tovar_img_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профиль пользователей'},
        ),
        migrations.AddField(
            model_name='basket',
            name='if_select',
            field=models.BooleanField(default=False, verbose_name='Выбран ли товар'),
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='name',
            field=models.CharField(help_text='Введите название товара (без названия категории)', max_length=255, verbose_name='Название'),
        ),
    ]
