# Generated by Django 5.1.1 on 2025-01-15 18:55

import django.core.validators
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_order_fcs_order_adress_order_adress_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
        migrations.AlterField(
            model_name='order',
            name='FCs',
            field=models.CharField(blank=True, help_text='Если способ доставки Почта России', max_length=250, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='order',
            name='adress',
            field=models.CharField(blank=True, help_text='Если способ доставки Почта России', max_length=550, null=True, verbose_name='Адрес пользователя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='adress_mail',
            field=models.CharField(blank=True, help_text='Если способ доставки Почта России', max_length=550, null=True, verbose_name='Адрес почтового отделения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coords',
            field=models.CharField(blank=True, help_text='Если способ доставки Самовывоз', max_length=50, null=True, verbose_name='Координаты магазина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='track_numbers',
            field=models.PositiveIntegerField(blank=True, help_text='Если способ доставки Почта России', null=True, validators=[django.core.validators.MaxValueValidator(99999999999999)], verbose_name='трек-номера'),
        ),
    ]
