# Generated by Django 5.0.3 on 2025-01-16 18:10

import django.core.validators
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_alter_img_tovar_img_alter_order_fcs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер карты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cvv',
            field=models.CharField(default=123, max_length=3, verbose_name='CVV'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='mm',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Месяц карты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='yy',
            field=models.PositiveIntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Год карты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
    ]
