# Generated by Django 5.0.3 on 2025-01-16 18:40

import django.core.validators
import django.db.models.deletion
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_order_card_number_order_cvv_order_mm_order_yy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sposob_dostavka',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('Pochta', 'Почта Росси')], max_length=9, verbose_name='Способ доставки'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='tovar_order',
        ),
        migrations.AddField(
            model_name='order',
            name='tovar_order',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.order_tovars', verbose_name='Товары заказа'),
            preserve_default=False,
        ),
    ]
