# Generated by Django 5.0.3 on 2025-01-16 18:44

import django.core.validators
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0042_alter_img_tovar_img_alter_order_sposob_dostavka_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='tovar_order',
        ),
        migrations.AddField(
            model_name='order',
            name='tovar_order',
            field=models.ManyToManyField(blank=True, to='polls.order_tovars', verbose_name='Товары заказа'),
        ),
    ]
