# Generated by Django 5.0.3 on 2025-01-16 18:50

import django.core.validators
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0043_alter_img_tovar_img_remove_order_tovar_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
        migrations.AlterField(
            model_name='order',
            name='card_number',
            field=models.CharField(max_length=19, verbose_name='Номер карты'),
        ),
    ]
