# Generated by Django 5.0.3 on 2025-01-16 18:52

import django.core.validators
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0044_alter_img_tovar_img_alter_order_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
        migrations.AlterField(
            model_name='order',
            name='FCs',
            field=models.CharField(blank=True, help_text='Если способ доставки "Почта России"', max_length=250, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='order',
            name='adress',
            field=models.CharField(blank=True, help_text='Если способ доставки "Почта России"', max_length=550, null=True, verbose_name='Адрес пользователя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='adress_mail',
            field=models.CharField(blank=True, help_text='Если способ доставки "Почта России"', max_length=550, null=True, verbose_name='Адрес почтового отделения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coords',
            field=models.CharField(blank=True, help_text='Если способ доставки "Самовывоз"', max_length=50, null=True, verbose_name='Координаты магазина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='track_numbers',
            field=models.CharField(blank=True, help_text='Если способ доставки "Почта России"', max_length=14, null=True, verbose_name='трек-номера'),
        ),
    ]
