# Generated by Django 5.0.3 on 2025-01-16 19:07

import django.core.validators
import django.utils.timezone
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_alter_img_tovar_img_alter_order_fcs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата заказа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата доставки/отмены'),
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coords',
            field=models.CharField(blank=True, help_text='Если способ доставки "Самовывоз"', max_length=250, null=True, verbose_name='Координаты магазина'),
        ),
    ]
