# Generated by Django 5.0.3 on 2025-01-19 14:51

import django.core.validators
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0048_order_tovars_t_cost_alter_img_tovar_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='errors',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Описать ошибку'),
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dostavka',
            field=models.CharField(choices=[('collect', 'Проверяется'), ('goes', 'Достовляется'), ('delivered', 'Доставлен'), ('received', 'Получен'), ('cancelled', 'Отменнено')], max_length=9, verbose_name='Доставка'),
        ),
    ]
