# Generated by Django 5.0.3 on 2025-01-24 16:50

import django.core.validators
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0051_order_order_number_alter_img_tovar_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='score_star',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='comments',
            name='updatee_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dostavka',
            field=models.CharField(choices=[('collect', 'Проверяется'), ('goes', 'Достовляется'), ('delivered', 'Доставлен'), ('received', 'Получен'), ('cancelled', 'Отменён')], max_length=9, verbose_name='Доставка'),
        ),
    ]
