# Generated by Django 5.0.3 on 2025-01-24 16:56

import django.core.validators
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0053_alter_comments_created_at_alter_comments_score_star_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='baned',
            field=models.BooleanField(default=1, verbose_name='Заблокировать коментарий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='baned_com',
            field=models.CharField(default=1, help_text='опишите причину блокировки пользователю', max_length=250, verbose_name='Причина блокировки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
    ]
