# Generated by Django 5.0.3 on 2025-01-24 17:08

import django.core.validators
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0054_comments_baned_comments_baned_com_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='score_star',
            new_name='star',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='updatee_at',
            new_name='update_at',
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
    ]
