# Generated by Django 5.0.3 on 2025-01-27 17:43

import datetime
import django.core.validators
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0063_comments_baned_date_alter_img_tovar_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='baned_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 20, 43, 27, 985557), verbose_name='Дата бана'),
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
    ]
