# Generated by Django 5.0.3 on 2025-02-10 11:50

import ckeditor.fields
import django.core.validators
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0073_tovars_descr_alter_img_tovar_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='descr',
            field=ckeditor.fields.RichTextField(blank=True, default=None, help_text='Описание товара', max_length=2000, null=True, verbose_name='Описание'),
        ),
    ]
