# Generated by Django 5.0.3 on 2025-02-19 12:59

import django.core.validators
import django.db.models.deletion
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0074_alter_img_tovar_img_alter_tovars_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='tovar',
            field=models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='polls.tovars'),
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='skidka_cost',
            field=models.IntegerField(blank=True, help_text='можно оставить пустым', null=True, verbose_name='Цена со скидкой'),
        ),
    ]
