# Generated by Django 5.0.3 on 2025-03-10 13:33

import django.core.validators
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0077_alter_comments_tovar_alter_img_tovar_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtor',
            name='seo',
            field=models.TextField(default=1, verbose_name='SEO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='seo',
            field=models.TextField(default=1, verbose_name='SEO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gl_category',
            name='seo',
            field=models.TextField(default=1, verbose_name='SEO'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='img_tovar',
            name='img',
            field=models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео'),
        ),
    ]
