# Generated by Django 5.0.3 on 2025-03-12 17:29

import django.core.validators
import django.db.models.deletion
import polls.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0078_avtor_seo_category_seo_gl_category_seo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комметарий товара', 'verbose_name_plural': 'Комметарии товаров'},
        ),
        migrations.AlterModelOptions(
            name='tovars',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='baned',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='baned_com',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='baned_date',
        ),
        migrations.AlterField(
            model_name='avtor',
            name='seo',
            field=models.TextField(help_text='Можете добавить ключевые слова (без дублирования названия производителя)', verbose_name='SEO'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='tovar',
            field=models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='polls.tovars'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='tovars', to='polls.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='skidka_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='можно оставить пустым', max_digits=12, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.CreateModel(
            name='ImgTovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(null=True, upload_to=polls.models.img_tovar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'svg', 'webp', 'gif', 'avi', 'flv', 'mp4', 'mpg'])], verbose_name='Картинка или видео')),
                ('is_video', models.BooleanField(default=False, help_text='ставиться автомитически. если нет, то поставте', verbose_name='Видео')),
                ('tovar', models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='polls.tovars')),
            ],
            options={
                'verbose_name': 'Картинка к товару',
                'verbose_name_plural': 'Картинки к товарам',
            },
        ),
        migrations.DeleteModel(
            name='img_tovar',
        ),
    ]
