# Generated by Django 5.0.3 on 2025-03-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0079_alter_comments_options_alter_tovars_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history_tovars',
            options={'ordering': ['-created_at'], 'verbose_name': 'История просмотра товаров', 'verbose_name_plural': 'Истории просмотров товаров'},
        ),
    ]
