# Generated by Django 5.0.3 on 2025-03-13 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0081_rename_gl_category_gl_category_main_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='polls.gl_category', verbose_name='Главная категория'),
        ),
    ]
