# Generated by Django 5.0.3 on 2025-03-15 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0082_alter_category_main_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='tovar',
            field=models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='polls.tovars'),
        ),
    ]
