# Generated by Django 5.0.3 on 2025-03-15 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0083_alter_basket_tovar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specs',
            name='tovar',
            field=models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='polls.tovars'),
        ),
    ]
