# Generated by Django 5.0.3 on 2025-03-19 13:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0084_alter_specs_tovar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together={('tovar', 'user')},
        ),
    ]
