# Generated by Django 5.0.3 on 2025-03-19 14:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0085_alter_comments_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together={('tovar', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='history_tovars',
            unique_together={('tovar', 'user')},
        ),
    ]
