# Generated by Django 5.0.3 on 2025-03-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0086_alter_basket_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='baned',
            field=models.BooleanField(default=False, verbose_name='Забанен'),
        ),
    ]
