# Generated by Django 5.0.3 on 2025-03-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0088_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mm',
        ),
        migrations.RemoveField(
            model_name='order',
            name='yy',
        ),
    ]
